### PR TITLE
Added class_alias for backwards compatibility

### PR DESCRIPTION
**Pull request by jonasraoni**

### CODE REVIEW

**Comment by jonasraoni** [comment]
@asmecher Just a small PR to fix the main branch.

**Comment by jonasraoni** [comment]
I was going to update the `version.xml` to include the namespace, but I decided to not add more unpredictability 😁

**Comment by NateWr** [comment]
Thanks @jonasraoni, I've committed the class alias and updated ojs/omp/ops. I wasn't sure why `index.php` was removed so I didn't want to commit that. But Alec can take a closer look.

**Comment by jonasraoni** [comment]
Looks like the `index.php` is deprecated, there's a custom loader here: https://github.com/pkp/pkp-lib/blob/main/classes/plugins/PluginRegistry.php#L297

**Comment by NateWr** [comment]
Ahh! So probably it doesn't need the `class_alias` if no `index.php` exists. I'll let Alec look and decide how to handle it.

**Comment by asmecher** [comment]
I'm missing the context here; was there an error message that this fixes?

**Comment by jonasraoni** [comment]
@asmecher Yes! There was an error.

Nate just got in doubt about dropping the `index.php`, but it can be done.

**Pull request closed without merging**
